import { CATEGORIES, categoryKey, concurrentDownloadLimitLabel, destinationLabel, duplicateHandlingLabel } from "./settings.js";

export class MainView {
  constructor({ onCategoryToggle, onRescan, onDownload, onOpenConfiguration }) {
    this.root = document.querySelector("#main-view"); this.pageStatus = document.querySelector("#page-status"); this.total = document.querySelector("#selection-total"); this.empty = document.querySelector("#empty-state"); this.result = document.querySelector("#result-status"); this.download = document.querySelector("#download-button"); this.destination = document.querySelector("#current-destination"); this.duplicate = document.querySelector("#current-duplicate"); this.concurrency = document.querySelector("#current-concurrency"); this.customToggles = document.querySelector("#custom-category-toggles"); this.onCategoryToggle = onCategoryToggle;
    this.toggles = [...document.querySelectorAll(".category-toggle")]; this.toggles.forEach((button) => button.addEventListener("click", () => onCategoryToggle(button.dataset.category))); document.querySelector("#rescan-button").addEventListener("click", onRescan); this.download.addEventListener("click", onDownload); ["#open-configuration-button", "#edit-settings-button"].forEach((selector) => document.querySelector(selector).addEventListener("click", onOpenConfiguration));
  }
  show() { this.root.hidden = false; } hide() { this.root.hidden = true; } setStatus(message = "", isError = false) { this.result.textContent = message; this.result.classList.toggle("error", isError); } setPageStatus(message) { this.pageStatus.textContent = message; }
  renderCustomToggles(customCategories, counts, selectedCategories) {
    this.customToggles.hidden = customCategories.length === 0;
    const ids = new Set(customCategories.map((category) => category.id)); [...this.customToggles.children].forEach((button) => { if (!ids.has(button.dataset.id)) button.remove(); });
    customCategories.forEach((category) => { const key = categoryKey(category); let button = [...this.customToggles.children].find((item) => item.dataset.id === category.id); if (!button) { button = document.createElement("button"); button.type = "button"; button.className = "category-toggle"; button.dataset.id = category.id; button.dataset.category = key; const name = document.createElement("span"); name.className = "category-name"; const icon = document.createElement("span"); icon.className = "category-icon"; icon.dataset.categoryIcon = "true"; icon.setAttribute("aria-hidden", "true"); const label = document.createElement("span"); label.dataset.categoryName = "true"; name.append(icon, label); const count = document.createElement("span"); count.className = "count"; button.append(name, count); button.addEventListener("click", () => this.onCategoryToggle(button.dataset.category)); this.customToggles.append(button); } button.querySelector("[data-category-icon]").textContent = category.icon || "🏷"; button.querySelector("[data-category-name]").textContent = category.name; button.lastElementChild.textContent = counts[key] || 0; button.setAttribute("aria-pressed", String(selectedCategories.has(key))); });
  }
  render({ links, selectedCategories, activeTabId, settings, customCategories }) {
    const categoryKeys = [...CATEGORIES, ...customCategories.map(categoryKey)]; const counts = Object.fromEntries(categoryKeys.map((category) => [category, 0])); links.forEach((link) => { if (link.category in counts) counts[link.category] += 1; }); CATEGORIES.forEach((category) => { document.querySelector(`[data-count="${category}"]`).textContent = counts[category]; }); this.toggles.forEach((button) => button.setAttribute("aria-pressed", String(selectedCategories.has(button.dataset.category)))); this.renderCustomToggles(customCategories, counts, selectedCategories);
    const total = links.filter((link) => selectedCategories.has(link.category)).length; this.total.textContent = `${total} selected file${total === 1 ? "" : "s"}`; this.download.textContent = `Download ${total} file${total === 1 ? "" : "s"}`; this.download.disabled = total === 0 || activeTabId === null; this.empty.hidden = links.length > 0 || activeTabId === null; this.destination.textContent = `Save location: ${destinationLabel(settings.destination)}`; this.duplicate.textContent = `If filename exists: ${duplicateHandlingLabel(settings.duplicateHandling)}`; this.concurrency.textContent = `Concurrent downloads: ${concurrentDownloadLimitLabel(settings.concurrentDownloadLimit)}`;
  }
}
