import { CATEGORIES, DEFAULT_SETTINGS, categoryKey, loadDownloadedFileCount, loadSettings, saveCustomCategories, saveSelectedFileTypes, saveSettings } from "./settings.js";
import { MainView } from "./main-view.js";
import { ConfigurationView } from "./configuration-view.js";
import { ReviewView } from "./review-view.js";
import { copyUrlManifest } from "./clipboard.js";
import { exportUrlManifest } from "./export-manifest.js";

const SCAN_REQUEST = "page-file-downloader:scan", DOWNLOAD_REQUEST = "page-file-downloader:download";
const BUILTIN_NAMES = { pdf: "PDF", images: "Images", docs: "Docs", media: "Media" };
let currentLinks = [], activeTabId = null, scanInProgress = null;
let settings = { destination: { ...DEFAULT_SETTINGS.destination }, duplicateHandling: DEFAULT_SETTINGS.duplicateHandling, concurrentDownloadLimit: DEFAULT_SETTINGS.concurrentDownloadLimit };
let customCategories = [], customCategorySelections = {}, selectedCategories = new Set(CATEGORIES), downloadedFileCount = 0;
const mainView = new MainView({ onCategoryToggle: toggleCategory, onRescan: () => scanCurrentTab({ announce: true }), onDownload: downloadAllEnabled, onReview: openReview, onOpenConfiguration: openConfiguration });
const configurationView = new ConfigurationView({ onBack: () => showMain("settings"), onSettingsChange: updateSettings, onCustomCategoriesChange: updateCustomCategories, onOpenDownloads: openDownloads, onError: (error) => mainView.setStatus(apiError(error, "Could not save configuration."), true) });
const reviewView = new ReviewView({ onBack: () => showMain("review"), onRefresh: refreshReview, onCopy: copyReviewed, onExport: exportReviewed, onDownload: downloadReviewed });
const overwriteDialog = document.querySelector("#overwrite-dialog");

function apiError(error, fallback) { return error?.message || fallback; }
function selectedFileTypes() { return Object.fromEntries(CATEGORIES.map((category) => [category, selectedCategories.has(category)])); }
function categoryName(categoryId) { return BUILTIN_NAMES[categoryId] || customCategories.find((category) => categoryKey(category) === categoryId)?.name || "Files"; }
function filenameForUrl(url, fallback) { try { const name = new URL(url).pathname.split("/").filter(Boolean).pop(); return name ? decodeURIComponent(name) : `Download ${fallback}`; } catch { return `Download ${fallback}`; } }
function normalizeSnapshot(links, enabledOnly = true) {
  const allowed = new Set([...CATEGORIES, ...customCategories.map(categoryKey)]), enabled = new Set(selectedCategories), unique = new Map();
  links.forEach((link, index) => { try { const parsed = new URL(link?.url); if (!/^https?:$/.test(parsed.protocol) || !allowed.has(link.category) || (enabledOnly && !enabled.has(link.category)) || unique.has(parsed.href)) return; unique.set(parsed.href, { url: parsed.href, filename: filenameForUrl(parsed.href, index + 1), domain: parsed.hostname || "Unknown site", categoryId: link.category, categoryName: categoryName(link.category) }); } catch { /* Ignore malformed scanner results. */ } });
  const order = new Map([...CATEGORIES, ...customCategories.map(categoryKey)].map((id, index) => [id, index])); return [...unique.values()].sort((left, right) => order.get(left.categoryId) - order.get(right.categoryId) || left.filename.localeCompare(right.filename, undefined, { sensitivity: "base" }) || left.url.localeCompare(right.url));
}
function render() { mainView.render({ links: currentLinks, selectedCategories, activeTabId, settings, customCategories, downloadedFileCount }); }
function toggleCategory(category) { if (selectedCategories.has(category)) selectedCategories.delete(category); else selectedCategories.add(category); mainView.setStatus(""); render(); if (CATEGORIES.includes(category)) void saveSelectedFileTypes(selectedFileTypes()); else { const id = category.slice("custom:".length); customCategorySelections[id] = selectedCategories.has(category); void saveCustomCategories(customCategories, customCategorySelections); } }
async function updateSettings(nextSettings) { settings = { destination: { ...nextSettings.destination }, duplicateHandling: nextSettings.duplicateHandling, concurrentDownloadLimit: nextSettings.concurrentDownloadLimit }; await saveSettings(settings); render(); }
async function updateCustomCategories(nextCategories) { const priorSelections = customCategorySelections; customCategories = nextCategories.map((category) => ({ ...category, extensions: [...category.extensions] })); customCategorySelections = Object.fromEntries(customCategories.map((category) => [category.id, priorSelections[category.id] !== false])); selectedCategories = new Set([...selectedCategories].filter((key) => !key.startsWith("custom:"))); customCategories.forEach((category) => { if (customCategorySelections[category.id]) selectedCategories.add(categoryKey(category)); }); await saveCustomCategories(customCategories, customCategorySelections); configurationView.customCategoriesView.render(customCategories); await scanCurrentTab({ force: true }); }
function openConfiguration() { reviewView.hide(); configurationView.show(settings, customCategories); mainView.hide(); }
function showMain(source = "settings") { configurationView.hide(); reviewView.hide(); mainView.show(); document.querySelector(source === "review" ? "#download-button" : "#open-configuration-button").focus(); render(); }
async function getActiveTab() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) throw new Error("No active browser tab is available."); return tab; }
async function scanSnapshot() { const tab = await getActiveTab(); activeTabId = tab.id; await chrome.scripting.executeScript({ target: { tabId: tab.id }, files: ["scanner.js"] }); const response = await chrome.tabs.sendMessage(tab.id, { type: SCAN_REQUEST, customCategories }); if (!response?.ok || !Array.isArray(response.links)) throw new Error(response?.error || "The page scanner did not return links."); return response.links; }
function scanCurrentTab({ announce = false, force = false } = {}) { if (scanInProgress) return force ? scanInProgress.then(() => scanCurrentTab({ announce })) : scanInProgress; scanInProgress = (async () => { try { currentLinks = await scanSnapshot(); mainView.setPageStatus(`Found ${currentLinks.length} supported link${currentLinks.length === 1 ? "" : "s"}.`); if (announce) mainView.setStatus("Scan updated."); return currentLinks; } catch (error) { activeTabId = null; currentLinks = []; mainView.setPageStatus("This page cannot be scanned."); mainView.setStatus(`${apiError(error, "Chrome blocked access to this page.")} Try a normal web page.`, true); return []; } finally { scanInProgress = null; render(); } })(); return scanInProgress; }
async function openReview() { mainView.setStatus(""); mainView.setPageStatus("Refreshing links for review…"); const snapshot = normalizeSnapshot(await scanCurrentTab({ force: true })); if (!snapshot.length) { mainView.setStatus("No enabled file links are available to review.", true); return; } mainView.hide(); reviewView.show(snapshot); }
async function downloadAllEnabled() {
  mainView.setStatus(""); mainView.setPageStatus("Refreshing links before download…"); const urls = normalizeSnapshot(await scanCurrentTab({ force: true })).map((item) => item.url);
  if (!urls.length) { mainView.setStatus("No enabled file links are available to download.", true); return; }
  if (settings.destination.mode === "ask" && urls.length > 1 && !window.confirm(`Chrome will open ${urls.length} Save As dialogs, one for each file. Continue?`)) { mainView.setStatus("Download canceled."); return; }
  if (settings.duplicateHandling === "overwrite" && !await confirmOverwrite()) { mainView.setStatus("Download canceled."); return; }
  try { const response = await chrome.runtime.sendMessage({ type: DOWNLOAD_REQUEST, urls, destination: { ...settings.destination }, duplicateHandling: settings.duplicateHandling, concurrentDownloadLimit: settings.concurrentDownloadLimit }); if (!response?.ok) throw new Error(response?.error || "The download request failed."); mainView.setStatus(`${urls.length} download${urls.length === 1 ? "" : "s"} queued. ${response.statusText || ""}`.trim()); } catch (error) { mainView.setStatus(apiError(error, "Could not start downloads."), true); } render();
}
async function refreshReview() { try { const links = await scanSnapshot(); currentLinks = links; reviewView.merge(normalizeSnapshot(links)); } catch (error) { document.querySelector("#review-notice").textContent = apiError(error, "Could not refresh page links."); } }
async function copyReviewed(urls) { try { await copyUrlManifest(urls); reviewView.setTemporaryNotice(`Copied ${urls.length} URL${urls.length === 1 ? "" : "s"} to clipboard.`); } catch { reviewView.setNotice("Could not copy URLs. Please try again."); } }
async function exportReviewed(urls) { if (settings.duplicateHandling === "overwrite" && !await confirmOverwrite({ title: "Replace existing export manifest?", message: "An export manifest with the same name may be replaced. Continue?" })) return; try { await exportUrlManifest({ urls, destination: settings.destination, duplicateHandling: settings.duplicateHandling }); reviewView.setTemporaryNotice(`Exported ${urls.length} URL${urls.length === 1 ? "" : "s"} as a text file.`); } catch { reviewView.setNotice("Could not export URLs. Please try again."); } }
function confirmOverwrite({ title = "Replace existing files?", message = "Files with matching names in the selected Downloads location may be replaced. Continue?" } = {}) { return new Promise((resolve) => { const trigger = document.activeElement, cancelButton = document.querySelector("#cancel-overwrite-button"), continueButton = document.querySelector("#continue-overwrite-button"), titleElement = document.querySelector("#overwrite-dialog-title"), messageElement = overwriteDialog.querySelector(".dialog-message"); titleElement.textContent = title; messageElement.textContent = message; const close = (confirmed) => { overwriteDialog.hidden = true; cancelButton.removeEventListener("click", cancel); continueButton.removeEventListener("click", proceed); overwriteDialog.removeEventListener("keydown", keydown); (trigger || document.querySelector("#download-button")).focus(); resolve(confirmed); }; const cancel = () => close(false), proceed = () => close(true), keydown = (event) => { if (event.key === "Escape") { event.preventDefault(); close(false); } }; cancelButton.addEventListener("click", cancel); continueButton.addEventListener("click", proceed); overwriteDialog.addEventListener("keydown", keydown); overwriteDialog.hidden = false; cancelButton.focus(); }); }
async function downloadReviewed(reviewedUrls) {
  if (!reviewedUrls.length) return; let finalLinks;
  try { finalLinks = normalizeSnapshot(await scanSnapshot(), false); currentLinks = finalLinks.map((item) => ({ url: item.url, category: item.categoryId })); } catch (error) { document.querySelector("#review-notice").textContent = apiError(error, "Could not confirm page links."); return; }
  const available = new Set(finalLinks.map((item) => item.url)), urls = reviewedUrls.filter((url) => available.has(url)), removed = reviewedUrls.length - urls.length;
  if (!urls.length) { document.querySelector("#review-notice").textContent = removed ? `${removed} selected link${removed === 1 ? " is" : "s are"} no longer available on this page.` : "No selected links are available to download."; return; }
  if (settings.destination.mode === "ask" && urls.length > 1 && !window.confirm(`Chrome will open ${urls.length} Save As dialogs, one for each file. Continue?`)) return;
  if (settings.duplicateHandling === "overwrite" && !await confirmOverwrite()) return;
  try { const response = await chrome.runtime.sendMessage({ type: DOWNLOAD_REQUEST, urls, destination: { ...settings.destination }, duplicateHandling: settings.duplicateHandling, concurrentDownloadLimit: settings.concurrentDownloadLimit }); if (!response?.ok) throw new Error(response?.error || "The download request failed."); showMain(); mainView.setStatus(`${urls.length} download${urls.length === 1 ? "" : "s"} queued.${removed ? ` ${removed} unavailable link${removed === 1 ? " was" : "s were"} skipped.` : ""} ${response.statusText || ""}`.trim()); } catch (error) { document.querySelector("#review-notice").textContent = apiError(error, "Could not start downloads."); } render();
}
async function openDownloads() { try { await chrome.downloads.showDefaultFolder(); const subfolder = settings.destination.mode === "subfolder" && settings.destination.subfolder; mainView.setStatus(subfolder ? "Chrome can open the Downloads folder, but not a specific subfolder." : "Opened Chrome's Downloads folder.", Boolean(subfolder)); } catch (error) { mainView.setStatus(apiError(error, "Could not open Chrome's Downloads folder."), true); } }
async function checkReviewPageChanges() { if (!reviewView.isOpen()) return; try { const next = normalizeSnapshot(await scanSnapshot()), now = new Set(next.map((item) => item.url)), before = new Set(reviewView.items.map((item) => item.url)); if (now.size !== before.size || [...now].some((url) => !before.has(url))) reviewView.notifyPageMayHaveChanged(); } catch { /* A transient scan failure should not disrupt review. */ } }
async function initialize() { try { const [restored, count] = await Promise.all([loadSettings(), loadDownloadedFileCount()]); settings = restored.settings; customCategories = restored.customCategories; customCategorySelections = restored.customCategorySelections; downloadedFileCount = count; selectedCategories = new Set(CATEGORIES.filter((category) => restored.selectedFileTypes[category])); customCategories.forEach((category) => { if (customCategorySelections[category.id]) selectedCategories.add(categoryKey(category)); }); } catch { /* Keep safe defaults if local storage is unavailable. */ } render(); document.body.classList.remove("is-loading"); scanCurrentTab(); }
initialize(); window.setInterval(() => reviewView.isOpen() ? checkReviewPageChanges() : scanCurrentTab(), 1000);
chrome.runtime.onMessage.addListener((message) => { if (message?.type === "page-file-downloader:queue-status") mainView.setStatus(message.statusText, Boolean(message.failed)); if (message?.type === "page-file-downloader:download-count") { downloadedFileCount = message.count; render(); } });
