function element(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }

export class ReviewView {
  constructor({ onBack, onRefresh, onDownload }) {
    this.root = document.querySelector("#review-view"); this.back = document.querySelector("#review-back-button"); this.summary = document.querySelector("#review-summary"); this.notice = document.querySelector("#review-notice"); this.groups = document.querySelector("#review-groups"); this.total = document.querySelector("#review-selected-total"); this.download = document.querySelector("#review-download-button"); this.items = []; this.selected = new Set();
    this.back.addEventListener("click", onBack); document.querySelector("#review-select-all").addEventListener("click", () => { this.selected = new Set(this.items.map((item) => item.url)); this.render(); }); document.querySelector("#review-select-none").addEventListener("click", () => { this.selected.clear(); this.render(); }); document.querySelector("#review-refresh").addEventListener("click", onRefresh); this.download.addEventListener("click", () => onDownload(this.selectedUrls()));
  }
  show(items) { this.items = items; this.selected = new Set(items.map((item) => item.url)); this.notice.textContent = ""; this.root.hidden = false; this.render(); this.back.focus(); }
  hide() { this.root.hidden = true; }
  isOpen() { return !this.root.hidden; }
  selectedUrls() { return this.items.filter((item) => this.selected.has(item.url)).map((item) => item.url); }
  notifyPageMayHaveChanged() { if (this.isOpen()) this.notice.textContent = "Page links may have changed. Refresh to update the list."; }
  merge(items) { const old = new Map(this.items.map((item) => [item.url, item])); const removedSelected = [...this.selected].filter((url) => !items.some((item) => item.url === url)).length; this.items = items; this.selected = new Set(items.filter((item) => old.has(item.url) && this.selected.has(item.url)).map((item) => item.url)); this.notice.textContent = removedSelected ? `${removedSelected} previously selected link${removedSelected === 1 ? " is" : "s are"} no longer available on this page.` : "Review list refreshed. New links are not selected."; this.render(); }
  render() {
    const count = this.selected.size; this.summary.textContent = `${this.items.length} file${this.items.length === 1 ? "" : "s"} found · ${count} selected`; this.total.textContent = `${count} selected`; this.download.textContent = `Download ${count} selected`; this.download.disabled = count === 0; this.groups.replaceChildren();
    for (const categoryId of [...new Set(this.items.map((item) => item.categoryId))]) {
      const items = this.items.filter((item) => item.categoryId === categoryId); const group = element("section", "review-group"); const header = element("div", "review-group-header"); const heading = element("h2", null, `${items[0].categoryName} (${items.length})`); const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.className = "review-group-checkbox"; checkbox.checked = items.every((item) => this.selected.has(item.url)); checkbox.indeterminate = !checkbox.checked && items.some((item) => this.selected.has(item.url)); checkbox.setAttribute("aria-label", `Select all ${items[0].categoryName} files`); checkbox.addEventListener("change", () => { items.forEach((item) => checkbox.checked ? this.selected.add(item.url) : this.selected.delete(item.url)); this.render(); }); header.append(heading, checkbox); group.append(header);
      for (const item of items) { const label = element("label", "review-row"); const input = document.createElement("input"); input.type = "checkbox"; input.checked = this.selected.has(item.url); input.setAttribute("aria-label", `${item.filename}, ${item.domain}, ${item.categoryName}. ${item.url}`); input.addEventListener("change", () => { input.checked ? this.selected.add(item.url) : this.selected.delete(item.url); this.render(); }); const details = element("span", "review-file-details"); const filename = element("span", "review-filename", item.filename); filename.title = item.url; const meta = element("span", "review-meta"); const domain = element("span", "review-domain", item.domain); domain.title = item.url; const badge = element("span", "review-badge", item.categoryName); meta.append(domain, badge); details.append(filename, meta); label.append(input, details); group.append(label); }
      this.groups.append(group);
    }
  }
}
