export const CATEGORIES = ["pdf", "images", "docs", "media"];
export const DEFAULT_SETTINGS = Object.freeze({ destination: Object.freeze({ mode: "default", subfolder: "" }), duplicateHandling: "uniquify" });
const DUPLICATE_HANDLING = new Set(["uniquify", "prompt", "overwrite"]);
export function validateSubfolder(value) { if (typeof value !== "string") return { ok: false, error: "The subfolder must be text." }; const trimmed = value.trim(); if (!trimmed) return { ok: true, value: "" }; if (/^[\\/]/.test(trimmed) || /^~/.test(trimmed) || /^[A-Za-z]:[\\/]/.test(trimmed)) return { ok: false, error: "Use a path relative to Chrome's Downloads folder." }; const segments = trimmed.replace(/\\/g, "/").split("/"); if (segments.some((segment) => !segment || segment === "." || segment === "..")) return { ok: false, error: "Subfolders cannot contain empty segments, . or ..." }; if (segments.some((segment) => /[<>:"|?*\u0000-\u001F]/.test(segment))) return { ok: false, error: "The subfolder contains invalid filename characters." }; return { ok: true, value: segments.join("/") }; }
export function normalizeSettings(saved = {}) { const duplicateHandling = DUPLICATE_HANDLING.has(saved.duplicateHandling) ? saved.duplicateHandling : DEFAULT_SETTINGS.duplicateHandling; const mode = ["default", "ask", "subfolder"].includes(saved.destination?.mode) ? saved.destination.mode : DEFAULT_SETTINGS.destination.mode; const subfolder = validateSubfolder(saved.destination?.subfolder); return { destination: { mode, subfolder: subfolder.ok ? subfolder.value : "" }, duplicateHandling }; }
export function normalizeSelectedFileTypes(savedTypes) { return Object.fromEntries(CATEGORIES.map((category) => [category, savedTypes?.[category] !== false])); }
export async function loadSettings() { const saved = await chrome.storage.local.get(["destination", "duplicateHandling", "selectedFileTypes"]); return { settings: normalizeSettings(saved), selectedFileTypes: normalizeSelectedFileTypes(saved.selectedFileTypes) }; }
export function saveSettings(settings) { return chrome.storage.local.set({ destination: settings.destination, duplicateHandling: settings.duplicateHandling }); } export function saveSelectedFileTypes(selectedFileTypes) { return chrome.storage.local.set({ selectedFileTypes }); }
export function destinationLabel(destination) { if (destination.mode === "ask") return "Ask for each file"; if (destination.mode === "subfolder") return `Downloads/${destination.subfolder || ""}`.replace(/\/$/, ""); return "Chrome default Downloads folder"; } export function duplicateHandlingLabel(value) { return { uniquify: "Keep both", prompt: "Ask me", overwrite: "Replace existing" }[value] || "Keep both"; } export function duplicateHandlingHelp(value) { return { uniquify: "Chrome creates a distinct filename, such as file (1).pdf.", prompt: "Chrome asks only when a filename conflict occurs.", overwrite: "Potentially destructive: matching target filenames may be replaced." }[value] || "Chrome creates a distinct filename, such as file (1).pdf."; }
